### ISSUE TITLE
Output directory in Windows

### ISSUE THREAD

**Issue by barukai** [Pirate-Crew/IPTV#13]
Innanzitutto complimenti per lo script, una bella idea. 
Volevo segnalare che se all'indirizzo del server alla fine aggiungo la porta (esempio ":8000"), il software si interrompe quando va a creare la directory in windows in quanto l'os non accetta i ":" per il nome del percorso. 
Visto che ho riscontrato in alcuni server la necessità di mettere il numero di porta altrimenti il software non riesce a fare l'attracco, pensavo magari di sostituire, in fase di creazione della directory, i ":" con un altro carattere accettato da windows (ad esempio "-").
Si può fare? 
Grazie

**Comment by Pinperepette** [comment]
appena riesco lo faccio, grazie per la segnalazione, non usando windows non
ci avevo pensato :)

Il giorno 6 gennaio 2016 10:48, barukai <notifications@github.com> ha
scritto:

> Innanzitutto complimenti per lo script, una bella idea
> Volevo segnalare che se all'indirizzo del server alla fine aggiungo la
> porta (esempio ":8000"), il software si interrompe quando va a creare la
> directory in windows in quanto l'os non accetta i ":" per il nome del
> percorso
> Visto che ho riscontrato in alcuni server la necessità di mettere il
> numero di porta altrimenti il software non riesce a fare l'attracco,
> pensavo magari di sostituire, in fase di creazione della directory, i ":"
> con un altro carattere accettato da windows (ad esempio "-")
> Si può fare?
> Grazie
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Pinperepette/IPTV/issues/13>.
>



-- 
I-I4ckeI2 ®
*Security Researcher*

"Voi potete fermare questo individuo, ma non potete fermarci tutti ... dopo
tutto, siamo tutti uguali."

http://pinperepette.it <http://pinperepette.it/info/>  *puoi contattarmi
anche a* pirata@pinperepette.it

**Comment by barukai** [comment]
Per risolvere basta aggiungere la seconda riga di codice come di seguito:

new_path = self.directory + "/" + URL.replace("http://", "")
new_path = new_path.replace(":", "-")

**Comment by vikingo11** [comment]
Ciao..anche io stesso problema con Windows..quando va a creare la directory mi va in errore..ho provato ad aggiungere la seconda riga come spiegato da barukai ma non mi apre ipvt con errore di line..come avete risolto voi?grazie

**Comment by vikingo11** [comment]
Ok risolto😉il passaggio è quello che ha scritto barukai..sbagliavo un carattere😉
