### ISSUE TITLE
Ricerca si interrompe

### ISSUE THREAD

**Issue by pquadri** [Pirate-Crew/IPTV#20]
Sembra che su tutti i server la ricerca si interrompa sempre più o meno allo stesso punto.
OS X El Capitan
Versione da riga di comando

**Comment by sicuro85** [comment]
anche a me stesso problema....
oltretutto non riesco a far andare la versione gui....
tu ci riesci????

**Comment by pquadri** [comment]
La versione GUI a me dà un errore su come è scritto il parser ma non riesco a modificarlo.
Non so come si possa fare a aggiungere un server alla lista

**Comment by Pinperepette** [comment]
per dargli in pasto un target (se non c'è l'opzione) è presente sicuramente nella versione dev https://github.com/Pirate-Crew/IPTV/tree/dev-dev se volete una ricerca velocissima, c'è la versione in c https://github.com/Pirate-Crew/IPTV-Extreme ma è più "rumorosa" :)
