### ISSUE TITLE
con l'ultimo aggiornamento non funziona non apre nulla

### ISSUE THREAD

**Issue by sicuro85** [Pirate-Crew/IPTV#21]
Last login: Sat Jan  9 14:37:33 on ttys000
MacBook-Pro-di-XXX:~ XXX$ cd Desktop
MacBook-Pro-di-XXX:Desktop XXX$ cd a
MacBook-Pro-di-XXX:a XXX$ cd IPTV
MacBook-Pro-di-XXX:IPTV XXX$ cd iptv
MacBook-Pro-di-XXX:iptv XXX$ python iptv.py
Traceback (most recent call last):
  File "iptv.py", line 4, in <module>
    import urllib2, urllib, google, sys, os, time , censys
  File "/Users/XXX/Desktop/a/IPTV/iptv/censys.py", line 3, in <module>
    import requests
ImportError: No module named requests
MacBook-Pro-di-XXX:iptv XXX$

**Comment by ludo237** [comment]
`Censys.py` è un file della dev-dev, sembra manchi il modulo requests, può essere un problema di requirements?

Ping @Pinperepette

**Comment by Vombato** [comment]
Ho forkato la soluzione, mancava il modulo requests che ho aggiunto ai requirements con "requests==2.9.1" basta poi lanciare un "pip install -r requirements.txt" e fa tutto da solo.

**Comment by sicuro85** [comment]
ho riprovato e continua a dare lo stesso errore nonostante abbia lanciato "pip install -r requirements.txt"

**Comment by sicuro85** [comment]
invece se lancio iptv_gui.py 
MacBook-Pro-di-XXX:iptv XXX$ python iptv_gui.py
Traceback (most recent call last):
  File "iptv_gui.py", line 26, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4
forse perché con el capitan non riesco ad installare PyQt4

**Comment by c1z** [comment]
prova ```pip install PyQt4```

**Comment by sicuro85** [comment]
pip install PyQt4
Collecting PyQt4
  Could not find a version that satisfies the requirement PyQt4 (from versions: )
No matching distribution found for PyQt4

**Comment by Pinperepette** [comment]
cerca install pyqt per il tuo sistema operativo... ti manca quella dipendenza :)

**Comment by Pinperepette** [comment]
per quanto riguarda Censys.py lo printa, per usare quella ricerca servono le api :)

**Comment by sicuro85** [comment]
mi risulta gia installato dalle brew infatti mi dice così:
pyqt-4.11.4 already installed
il censys a cosa serve??? che api ti servono???
