### ISSUE TITLE
Exception raised when the search end

### ISSUE THREAD

**Issue by Favacotta** [Pirate-Crew/IPTV#23]
Buonasera ragazzi, stavo provando la versione di iptv.py aggiornata qualche ora fa dal buon Ludo, vorrei segnalare che a fine ricerca viene proposto questo messaggio : Ops something went wrong! 
Scusate l'intrusione e grazie per il lavoro che fate

**Comment by ludo237** [comment]
Tecnicamente no. Significa che urlib2 non è riuscità a fetchare un link per ragioni generiche, però in effetti il messaggio spiega poco, cercherò di migliorare il feedback dal client.

**Comment by Favacotta** [comment]
se per andare a buon fine intendi la creazione di quello che trova nella cartella output ti dico sì.....

**Comment by ludo237** [comment]
@Favacotta perciò viene creato l'output ma lancia comunque l'eccezione. Indago!

**Comment by Favacotta** [comment]
dove mi ha trovato qualcosa sì, non ho capito bene una cosa ( nonostante la spiegazione del pirata ) ma non necessariamente i #### nella ricerca indicano che ha trovato qualcosa, confermate? Altrimenti c'è un errore :s

**Comment by ludo237** [comment]
@Favacotta No, non indicano che ha trovato qualcosa, ma semplicemente che sta usando tutti i nomi per fare il brute force.

**Comment by Favacotta** [comment]
Ok! Giusto perché il video del pirata accennava a qualcosa del genere ;)

**Comment by SniperWeek** [comment]
Menu
0 - Exit
1 - Search for some Servers
2 - Look at the servers list
3 - Select language, default is Italian
4 - Brute force random server
5 - Brute force specific server

Please select an option: 1
Fetching URLs plase wait...
Done, 30 URLs founded

################
##### IPTV #####
##### v1.2.2 ###
################

Menu
0 - Exit
1 - Search for some Servers
2 - Look at the servers list
3 - Select language, default is Italian
4 - Brute force random server
5 - Brute force specific server

Please select an option: 2
Printing server list
[0] - http://iptv.controlliamo.com:1980
[1] - http://iptvprotocol.dyndns.info
[2] - http://avik.bismarket.ru
[3] - http://best.bismarket.ru
[4] - http://xstream.teknohd.tv:8000
[5] - http://www.nqashalhob.com
[6] - http://pippotv.dyndns.tv:8000
[7] - http://37.187.253.239
[8] - http://iptv.euroremix.com:8000
[9] - http://diag-automobile.com
[10] - http://miraggio.dyndns.org:8000
[11] - http://149.202.203.48:24000
[12] - http://www.digital-eliteboard.com
[13] - http://kqyrshlir.com:21000
[14] - http://www.xtream-codes.com
[15] - http://iptv.wssiptv.com
[16] - http://www.t12v.com:8000
[17] - http://37.187.139.155:8000
[18] - http://94.23.49.84:8000
[19] - http://iptv-world.ddns.net:8000
[20] - http://sat.010e.net:8000
[21] - http://pro.darking.cloudns.pro:8000
[22] - http://frgart.ru
[23] - http://5.39.72.163
[24] - http://server.hitlantv.com:8080
[25] - http://217.79.191.18:8000
[26] - http://tvservice.broke-it.net
[27] - http://www.magikserv.com
[28] - http://promo.dyndns.biz:8000
[29] - https://github.com

################
##### IPTV #####
##### v1.2.2 ###
################

Menu
0 - Exit
1 - Search for some Servers
2 - Look at the servers list
3 - Select language, default is Italian
4 - Brute force random server
5 - Brute force specific server

Please select an option: 4
Fetching account from http://5.39.72.163 this might take a while.
Ops something went wrong!

################
##### IPTV #####
##### v1.2.2 ###
################

Menu
0 - Exit
1 - Search for some Servers
2 - Look at the servers list
3 - Select language, default is Italian
4 - Brute force random server
5 - Brute force specific server

Please select an option:

**Comment by ludo237** [comment]
Non fornite link esterni! Ora provo a fare dei test più intensi

**Comment by Tonyrock90** [comment]
Ludo237 se a te va su windows il problema forse a noi sta alla base, magari abbiamo sbagliato qualcosa. Ci puoi fornire tutti i comandi da inserire partendo dall'installazione di python?
tenendo conto che la cartella sta sul desktop.
Tipo installate python in c: e inserite nelle varabili d'ambiente ->path ->C:\Python27 ecc.
Lo so sarà una noia, ma almeno non fai test instensi.

**Comment by ludo237** [comment]
@Tonyrock90 Non uso Windows è quello il problema, tirerò su una VM per provare

**Comment by bigol** [comment]
Grazie per il lavoro, crea cartella di output, ma non arriva a verificare il 100% delle chiavi. si ferma al 30% circa  poi "Ops something went wrong!"

**Comment by Tonyrock90** [comment]
okok, io nel frattempo ho installato ubuntu 14 per vedere se funge lì

**Comment by Tonyrock90** [comment]
Ho risolto l'errore aggiornando la versione di ubuntu
