### ISSUE TITLE
Help with Windows and specific server attack

### ISSUE THREAD

**Issue by Tonyrock90** [Pirate-Crew/IPTV#24]
Salve, volevo alcune info, scrivo python iptv.py,digito:
 1 mi cerca i 30 server; 
 2 me li mostra;
3 la lingua italiana non si cambia ,rimane inglese,nonostante dica che sia stata cambiata; 
4 il server che forza è quasi sempre lo stesso e alla fine  dice  ETA[sec]: 945.327 Ops something went wrong!;
 5 mi da: 
Please select an option: 5
Please provide the number near the URLs founded: http:/nome_server
Traceback (most recent call last):
  File "C:\Users\tonyr\iptv.py", line 53, in <module>
    index = int(raw_input("Please provide the number near the URLs founded: "))
ValueError: invalid literal for int() with base 10: 'http://nome_server'
come risolvo , ho messo le variabili d'ambiente e ho installato pip e pyqt.exe

**Comment by ludo237** [comment]
Ciao.
Punti 1, 2 è normale.
Il punto 3 cambia la lingua del file names.txt utilizzato, non quella di sistema. Provvederò a specificarlo meglio nel menù.
Il punto 5 si aspetta **il numero** vicino all url che vuoi attaccare, che lo trovi con l'opzione 2, e non l'url a stringa. Però interessante eccezione, la implemento!.

Per il punto 4 devo riprodurre l'errore.

**Comment by Tonyrock90** [comment]
ok, grazie per i chiarimenti, ora testo e ti aggiorno, seno non riesci a riprodurre l'errore ti posso ospitare con teamviewer. Grazie ancora.

**Comment by ludo237** [comment]
Nel caso si ripresenti l'errore 4, riapro l'issue

**Comment by Tonyrock90** [comment]
si è ripetuto Ops something went wrong!

**Comment by ludo237** [comment]
NON devi aprire il crawler, solo lavorare con il cli py. è normale che non puoi aprire il crawler è una classe!

**Comment by ludo237** [comment]
Comunque non apro l'issue referenzio #22
