### ISSUE TITLE
Video Player for .m3u files

### ISSUE THREAD

**Issue by Kingem39p** [Pirate-Crew/IPTV#26]
salve, avevo solo un dubbio.

ho scannato un pò, da diversi server, e ho trovato un pò di liste.

aprendole, vedo un codice HTML. Cosa devo fare per farle diventare liste m3u normali?

grazie.

**Comment by Kingem39p** [comment]
Credo siano cryptate, o qualcosa del genere, perchè alcune le trovo normali. 

sapete dirmi da cosa dipende, o comunque se è un bug o errore mio? grazie

**Comment by ludo237** [comment]
Hai provato [VLC](http://www.videolan.org/vlc/)?

**Comment by Kingem39p** [comment]
@ludo237 ciao scusami per la risposta un pò in ritardo, io uso solo VLC. ma essendo un file scritto in html (pur avendo l'estensione m3u) non riproduce le liste, come le normali m3u.

**Comment by Tonyrock90** [comment]
mi sembra strano, se fai apri con vlc si dovrebbe aprire. se non si vede il server non è buono.

**Comment by Kingem39p** [comment]
@Tonyrock90 , ti ho inviato un'email.

comunque sia, non riesco a vederlo, e vedendo il source è scritto in html! cosa molto strana. Per questo vlc non la legge.
