### ISSUE TITLE
Language file error

### ISSUE THREAD

**Issue by Kingem39p** [Pirate-Crew/IPTV#27]
con lo script in python, è da qualche giorno che mi da con tutti i server sempre lo stesso errore:

Cannot open the current Language file. Try another one

la mia domanda è: sono i server, o è successo qualcosa al language file o qualcosa del genere?

grazie.

**Comment by qwerty159** [comment]
Quale versione dello script stai usando? Master o dev?

**Comment by Kingem39p** [comment]
scusami non ho capito, io ho scaricato questa: " git clone git@github.com:Pirate-Crew/IPTV.git " 

e ogni volta che faccio uno scan di qualsiasi server mi da questo errore. Prima uscivano anche un paio di output, ora ne escono pochi per via di questo problema.

**Comment by qwerty159** [comment]
Prova a ricaricare il pacchetto da qui: https://github.com/Pirate-Crew/IPTV/archive/v1.2.3.zip

**Comment by Kingem39p** [comment]
@qwerty159 lo ho appena provato, posso confermarti che non è cambiato nulla.

p.s: agli inizi funzionava, adesso è da un paio di giorni che fa così.

**Comment by ludo237** [comment]
No! Il file di lingua è per settare quali nomi usare dalla cartella `languages` non ha nulla a che vedere con i server

**Comment by Danieleeee** [comment]
Salve,
ho appena scaricato dalla cartella Master ed ho lo stesso problema:
![1](https://user-images.githubusercontent.com/22749175/29962855-f32d1732-8f04-11e7-9db8-aab68a775f3a.png)
