### ISSUE TITLE
soluzione? opzione 6

### ISSUE THREAD

**Issue by Tonyrock90** [Pirate-Crew/IPTV#28]
su ubuntu va. grazie. solo che il punto 6 non funge, mi rilascia 
6 - Provide a random server to attack

Please select an option: python iptv.py http://indirizzo.com/
Traceback (most recent call last):
  File "iptv.py", line 32, in <module>
    choosenMenu = int(raw_input("Please select an option: "))
ValueError: invalid literal for int() with base 10: 'python iptv.py http://indirizzo.com/'
tony@System:~/Scrivania/IPTV-master/iptv$ python iptv.py

**Comment by Tonyrock90** [comment]
ho provato anche il comando  pip install --upgrade -r requirements.txt, ma la situazione non cambia. Ma voi python lo avete in usr/local/lib/python2.7/dist-packages ? o in  usr/lib/python2.7/dist-packages

**Comment by Kingem39p** [comment]
Il punto 6, anche se non funziona non ti preoccupare, perché ancora non è stato implementato.

infatti, se comunque funzionasse, ti uscirebbe scritto "coming soon...".

**Comment by Tonyrock90** [comment]
mi esce coming soon

**Comment by Kingem39p** [comment]
quindi hai risolto?

**Comment by Tonyrock90** [comment]
Please select an option: 6   
coming soon...

################
##### IPTV #####
##### v1.2.3 ###
################

Menu
0 - Exit
1 - Search for some Servers
2 - Look at the servers list
3 - Select language, default is Italian
4 - Brute force random server from the list
5 - Brute force specific server from the list
6 - Provide a random server to attack

Please select an option: python iptv.py http://indirizzo/
Traceback (most recent call last):
  File "iptv.py", line 32, in <module>
    choosenMenu = int(raw_input("Please select an option: "))
ValueError: invalid literal for int() with base 10: 'python iptv.py http://indirizzo/'
tony@System:~/Scrivania/IPTV-master/iptv$

**Comment by Tonyrock90** [comment]
nono

**Comment by Kingem39p** [comment]
Please select an option: python iptv.py http://indirizzo/
Traceback (most recent call last):
File "iptv.py", line 32, in 
choosenMenu = int(raw_input("Please select an option: "))
ValueError: invalid literal for int() with base 10: 'python iptv.py http://indirizzo/'
tony@System:~/Scrivania/IPTV-master/iptv$

**Comment by Tonyrock90** [comment]
Si, non scrivo indirizzo, ma il link del server

**Comment by Tonyrock90** [comment]
Scrivo indirizzo perché non so se si può inserire il sito

**Comment by Kingem39p** [comment]
Ho capito.

non devi scrivere " python iptv.py http://indirizzo/ " perché è già avviato il programma in python, quando il programma ti dice " Please select an option:  " intende tra quelle da 1 a 6 che ti dà sopra.

**Comment by Tonyrock90** [comment]
Si, non scrivo indirizzo, ma il link del server

**Comment by Kingem39p** [comment]
non devi scriverlo, se c'è scritto " please select an option: " devi mettere il numero dell'operazione che vuoi effettuare, ad esempio 1 per scan, 2 per vedere le liste ecc...

potresti comunque darmi una tua email? per scriverti in privato

**Comment by Tonyrock90** [comment]
lo so , ma il punto 6 ti fa fare la ricerca su un sito a tua scelta che non è nei 30 della lista

**Comment by Kingem39p** [comment]
si ma se non è ancora stato implementato non puoi usare il punto 6.

**Comment by Tonyrock90** [comment]
tonyrock90@hotmail.it

**Comment by ludo237** [comment]
Il punto 6 è in sviluppo. Sono in giro per lavoro in questo periodo

**Comment by Tonyrock90** [comment]
ah ok grazie
