### ISSUE TITLE
How to execute iptv_gui.py?

### ISSUE THREAD

**Issue by Kingem39p** [Pirate-Crew/IPTV#29]
Salve, ancora una volta eccomi quì, con un'altro dubbio.

non riesco veramente a capire come fare per eseguire il programma in python "iptv_gui.py".

sicuramente non ci arrivo io, per questo vi chiedo un piccolo aiuto sempre accettato.

grazie mille!

**Comment by qwerty159** [comment]
Usi Linux?

**Comment by Kingem39p** [comment]
Vorrei usare Windows sinceramente, però anche per linux non mi dispiacerebbe, se possibile.

**Comment by ludo237** [comment]
Ti da qualche errore?

**Comment by Armax** [comment]
https://twitter.com/arm4x/status/692030452199264256

**Comment by geggiot** [comment]
io utilizzavo il branch master e non riuscivo ad usare la versione gui, poi ho scaricato il branch dev-dev ed ho risolto

**Comment by 0adbylad** [comment]
Hello ...Ive been trying to get this software running now for days ...done a lot of reading..followed the above advice and got further than i have before 
But now
Traceback (most recent call last):
  File "iptv.py", line 4, in <module>
    import urllib2, urllib, google, sys, os, time , censys
  File "/Users/robingoodfellow/Downloads/IPTV-dev-dev/iptv/censys.py", line 3, in <module>
    import requests
ImportError: No module named requests

Anyone HELP!

**Comment by 0adbylad** [comment]
Found the answer
sudo easy_install -U requests

**Comment by 0adbylad** [comment]
Ive now found another problem
The script tries to run pyqt4 but if you've started from the beginning of the tutorial you would have downloaded the latest version which is 5
and then the script fails at line 26
