### ISSUE TITLE
Errore mkdir Windows

### ISSUE THREAD

**Issue by sup3rgiu** [Pirate-Crew/IPTV#30]
Su Windows non riesce a creare la cartella del sito nella cartella output. Penso che sia perchè su Windows i nome delle cartelle/file non possono contenere i due punti.

Allego uno screen dell'errore: http://prntscr.com/9upilf

EDIT: confermo, è colpa dei due punti. Ho editato lo script facendo un replace anche dei due punti e ora funziona.

Basta modificare la linea 209 in:
```python
nodoublepoint = URL.replace(":", "")
nodoublepoint = nodoublepoint.replace("http//", "")
new_path = directory + "/" + nodoublepoint
```

**Comment by ludo237** [comment]
Se la tua modifica funziona per favore apri una Pull request :+1:

**Comment by Tonyrock90** [comment]
alla linea 209 c'è new_path = directory + "/" + URL.replace(":", "")
                        new_path = self.directory + "/" + URL.replace("http://", "")
                        new_path = new_path.replace(+", "+)
se lo sostituisco non si avvia proprio +

**Comment by sup3rgiu** [comment]
A che file ti riferisci? Io mi riferisco al file iptv_gui.py (https://github.com/Pirate-Crew/IPTV/blob/dev-dev/iptv/iptv_gui.py) e come puoi notare in questo file c'è solo

```python
new_path = directory + "/" + URL.replace("http://", "")
```

**Comment by Tonyrock90** [comment]
mi riferivo alla versione dev

**Comment by Tonyrock90** [comment]
non va nemmeno la normale, non si apre il file

**Comment by Tonyrock90** [comment]
if len(the_page) > 0:
                        tr = (tr + 1)
                        msg = "account found !!! "
                        self.segnale()
                        nodoublepoint = URL.replace(":", "")
                        nodoublepoint = nodoublepoint.replace("http//", "")
                        new_path = directory + "/" + nodoublepoint
 if os.path.exists(new_path) is False:

**Comment by sup3rgiu** [comment]
Prova con questo file: https://www.sendspace.com/file/w729o3

**Comment by Tonyrock90** [comment]
ma anche a te all' avvio da questo C:\Python27\lib\site-packages\bs4\__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))

**Comment by sup3rgiu** [comment]
SI anche a me compare, ma puoi ignorarlo

**Comment by Tonyrock90** [comment]
grande, va, ma a te la versione iptv.py da errore ops,qualcosa è andato storto?

**Comment by sup3rgiu** [comment]
Quand'è che ti compare questo errore? Comunque io uso sempre la GUI

**Comment by Tonyrock90** [comment]
durante la ricerca, e la cosa bella è che l'altro ieri ho installato ubuntu e lì andava. ieri si è aggiornato ubuntu ed è uscito fatal error, oggi l'ho reinstallato e anche lì lo stesso errore.

**Comment by Tonyrock90** [comment]
cmq anche gui si impalla, però qualcosa trova

**Comment by sup3rgiu** [comment]
Sinceramente non ho avuto problemi a installare i requirements su Ubuntu, quindi non so che dirti.

In che senso si impalla? I nomi si bloccano e non scorrono più?

**Comment by ludo237** [comment]
Gli issue non sono una chat....
