### ISSUE TITLE
errore- ubuntu- pip install -r requirements.txt - Ops something went wrong!

### ISSUE THREAD

**Issue by Tonyrock90** [Pirate-Crew/IPTV#31]
```
tony@tony-System-Product-Name:~$ cd /home/tony/Scrivania/IPTV-master/iptv tony@tony-System-Product-Name:~/Scrivania/IPTV-master/iptv$ pip install -r requirements.txt
Collecting pyprind==2.9.3 (from -r requirements.txt (line 1))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached PyPrind-2.9.3.zip
Collecting google==1.7 (from -r requirements.txt (line 2))
  Using cached google-1.7-py2-none-any.whl
Collecting psutil==3.3.0 (from -r requirements.txt (line 3))
  Using cached psutil-3.3.0.tar.gz
Collecting clint==0.5.1 (from -r requirements.txt (line 4))
  Using cached clint-0.5.1.tar.gz
Collecting colored==1.2.1 (from -r requirements.txt (line 5))
  Using cached colored-1.2.1.tar.gz
Collecting tqdm==3.4.0 (from -r requirements.txt (line 6))
  Using cached tqdm-3.4.0-py2.py3-none-any.whl
Collecting beautifulsoup4 (from google==1.7->-r requirements.txt (line 2))
  Using cached beautifulsoup4-4.4.1-py2-none-any.whl
Collecting args (from clint==0.5.1->-r requirements.txt (line 4))
  Using cached args-0.1.0.tar.gz
Building wheels for collected packages: pyprind, psutil, clint, colored, args
  Running setup.py bdist_wheel for pyprind ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t_cfpX/pyprind/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpY8Agvlpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pyprind
  Running setup.py clean for pyprind
  Running setup.py bdist_wheel for psutil ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t_cfpX/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpQWqmlfpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for psutil
  Running setup.py clean for psutil
  Running setup.py bdist_wheel for clint ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t_cfpX/clint/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpJpPFqipip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for clint
  Running setup.py clean for clint
  Running setup.py bdist_wheel for colored ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t_cfpX/colored/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpe6QjRupip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for colored
  Running setup.py clean for colored
  Running setup.py bdist_wheel for args ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t_cfpX/args/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpJyWAeapip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for args
  Running setup.py clean for args
Failed to build pyprind psutil clint colored args
Installing collected packages: pyprind, beautifulsoup4, google, psutil, args, clint, colored, tqdm
  Running setup.py install for pyprind ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t_cfpX/pyprind/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-zuLvnr-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-i686-2.7
    creating build/lib.linux-i686-2.7/pyprind
    copying pyprind/__init__.py -> build/lib.linux-i686-2.7/pyprind
    copying pyprind/generator_factory.py -> build/lib.linux-i686-2.7/pyprind
    copying pyprind/prog_class.py -> build/lib.linux-i686-2.7/pyprind
    copying pyprind/progbar.py -> build/lib.linux-i686-2.7/pyprind
    copying pyprind/progpercent.py -> build/lib.linux-i686-2.7/pyprind
    running install_lib
    creating /usr/local/lib/python2.7/dist-packages/pyprind
    error: could not create '/usr/local/lib/python2.7/dist-packages/pyprind': Permission denied
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-t_cfpX/pyprind/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-zuLvnr-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-t_cfpX/pyprind
```

**Comment by Tonyrock90** [comment]
è pura sfiga ieri andava, oggi ho dovuto reinstallare ubuntu e non so cosa ho dimenticato .

**Comment by Kingem39p** [comment]
Prova ad installarli manualmente uno ad uno, un esempio:

pip install google==1.7

e vedi quale di questi 6 requirements da installare ti da il problema.

**Comment by Tonyrock90** [comment]
tony@tony-System-Product-Name:~$ cd /home/tony/Scrivania/IPTV-master/iptv 
tony@tony-System-Product-Name:~/Scrivania/IPTV-master/iptv$ pip install google==1.7 ubuntu
Requirement already satisfied (use --upgrade to upgrade): google==1.7 in /usr/local/lib/python2.7/dist-packages
Collecting ubuntu
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement ubuntu (from versions: )
No matching distribution found for ubuntu
tony@tony-System-Product-Name:~/Scrivania/IPTV-master/iptv$ pip --version
pip 8.0.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
tony@tony-System-Product-Name:~/Scrivania/IPTV-master/iptv$ pip install --upgrade google==1.7 ubuntu
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: google==1.7 in /usr/local/lib/python2.7/dist-packages
Collecting ubuntu
  Could not find a version that satisfies the requirement ubuntu (from versions: )
No matching distribution found for ubuntu

**Comment by Tonyrock90** [comment]
non va, secondo me ho la versione sbagliata di pip

**Comment by Tonyrock90** [comment]
@Armax @Pinperepette @ludo237

**Comment by ludo237** [comment]
Ora guardo i log che hai postato

**Comment by Tonyrock90** [comment]
ok, grazie mille, cmq inserendo il comando sudo pip install --upgrade google-api-python-client è scomparso l'errore Failed building wheel for pyprind

**Comment by Kingem39p** [comment]
di ubuntu capisco veramente poco, usando praticamente al 97% CentOS. 

devi provare anche gli altri requirements, non solo google. 

se gli altri non ti danno errori, il problema è il primo.

**Comment by ludo237** [comment]
Allora, python è un po una rogna su questo, il problema non è relativo al software ma alla configurazione del tuo ambiente, alcune possibili cause possono essere:

- Stai usando una versione vecchia di pip (minore della 6.1.1) e Python 2.7
- Hai più copie di Python 2.7 installate (prova a verificare questo punto)

Prova questi comandi

```sh
$ python -m pip uninstall pip setuptools
$ pacman install python-pip python-setuptools
```

sostituisci `pacman` con il pacchetto che stai usando (apt, yum o qualsiasi altro)

Poi prova

```sh
$ pip install setuptools --upgrade
```

**Comment by Tonyrock90** [comment]
ho provato il comando t
ony@tony-System-Product-Name:~/Scrivania/IPTV-master/iptv$ sudo pip install -r requirements.txt
[sudo] password for tony: 
The directory '/home/tony/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/tony/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): pyprind==2.9.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): google==1.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Collecting psutil==3.3.0 (from -r requirements.txt (line 3))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading psutil-3.3.0.tar.gz (261kB)
    100% |████████████████████████████████| 262kB 698kB/s 
Collecting clint==0.5.1 (from -r requirements.txt (line 4))
  Downloading clint-0.5.1.tar.gz
Collecting colored==1.2.1 (from -r requirements.txt (line 5))
  Downloading colored-1.2.1.tar.gz
Collecting tqdm==3.4.0 (from -r requirements.txt (line 6))
  Downloading tqdm-3.4.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from google==1.7->-r requirements.txt (line 2))
Collecting args (from clint==0.5.1->-r requirements.txt (line 4))
  Downloading args-0.1.0.tar.gz
Installing collected packages: psutil, args, clint, colored, tqdm
  Running setup.py install for psutil ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-iffW2I/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-sNcQu0-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-i686-2.7
    creating build/lib.linux-i686-2.7/psutil
    copying psutil/__init__.py -> build/lib.linux-i686-2.7/psutil
    copying psutil/_pslinux.py -> build/lib.linux-i686-2.7/psutil
    copying psutil/_compat.py -> build/lib.linux-i686-2.7/psutil
    copying psutil/_pssunos.py -> build/lib.linux-i686-2.7/psutil
    copying psutil/_common.py -> build/lib.linux-i686-2.7/psutil
    copying psutil/_psbsd.py -> build/lib.linux-i686-2.7/psutil
    copying psutil/_psosx.py -> build/lib.linux-i686-2.7/psutil
    copying psutil/_pswindows.py -> build/lib.linux-i686-2.7/psutil
    copying psutil/_psposix.py -> build/lib.linux-i686-2.7/psutil
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-i686-2.7
    creating build/temp.linux-i686-2.7/psutil
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_VERSION=330 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-i686-2.7/psutil/_psutil_linux.o
    psutil/_psutil_linux.c:12:20: fatal error: Python.h: File o directory non esistente
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-iffW2I/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-sNcQu0-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-iffW2I/psutil

**Comment by Tonyrock90** [comment]
tony@tony-System-Product-Name:~/Scrivania/IPTV-master/iptv$ python iptv.py 
Traceback (most recent call last):
  File "iptv.py", line 4, in <module>
    from clint.textui import colored

**Comment by ludo237** [comment]
L'output ti dice chiaramente qual'è il problema

`The directory '/home/tony/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.`

**Comment by Tonyrock90** [comment]
come versione ho pip 8.0.2 from /usr/local/lib/python2.7/dist-packages (python 2.7). Ora faccio come hai detto tu su

**Comment by Tonyrock90** [comment]
python è in /usr/local/lib/python2.7; in /usr/lib/python2.7 e lì c'è anche /usr/lib/python3

**Comment by Tonyrock90** [comment]
allora se faccio pip install setuptools  dice tony@tony-System-Product-Name:~$ pip install setuptools --upgrade
Il programma "pip" non è attualmente installato.  È possibile installarlo digitando:
sudo apt-get install python-pip
tony@tony-System-Product-Name:~$ sudo apt-get install python-pip
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
python-pip è già alla versione più recente.
0 aggiornati, 0 installati, 0 da rimuovere e 4 non aggiornati.
tony@tony-System-Product-Name:~$

**Comment by Tonyrock90** [comment]
se digito pip rilascia Il programma "pip" non è attualmente installato.  È possibile installarlo digitando:
apt-get install python-pip

**Comment by ludo237** [comment]
E' normale, hai PIP sotto sudo e cerchi di usarlo senza sudo nel primo comando.

**Comment by Tonyrock90** [comment]
nemmeno andava l'ho dovuto reinstallare con il comando sudo easy_install pip

**Comment by ludo237** [comment]
Si ma ripeto, è il tuo ambiente che è impostato male. dovresti evitare di installare componenti tramite sudo **se non strettamente necessario**

**Comment by Tonyrock90** [comment]
si ma io lo uso solo se dice che non ho i requisiti di root

**Comment by Tonyrock90** [comment]
allora usando pip install -r requirements.txt mi dava lo stesso errore di sopra, poi ho usato pip install --upgrade -r requirements.txt e non andava, poi sudo pip install --upgrade -r requirements.txt e stavolta è partitio

**Comment by Tonyrock90** [comment]
funge.grazie a tutti

**Comment by Tonyrock90** [comment]
a differenza di l'altro ieri ne trova uno solo e poi mi da l'errore Ops something went wrong!

**Comment by Kingem39p** [comment]
quello credo sia per colpa dei server, perché a me dà l'errore Language.

**Comment by Tonyrock90** [comment]
non credo, cmq a te va la versione gui? @Kingem39p

**Comment by Tonyrock90** [comment]
l'errore language? ma hai provato a impostare il linguaggio premendo 3?

**Comment by Kingem39p** [comment]
Non si sa come mai, ma adesso funziona come prima. ovvero si blocca un pò prima della metà, dando un errore: "Ops something went wrong!".

è capitato a molti questo errore, ma non so la soluzione.

**Comment by Tonyrock90** [comment]
Ho risolto semplicemente aggiornando la release...ovvero sono passato dalla 12 alla 14
