### ISSUE TITLE
git clone IPTV_GUY.py

### ISSUE THREAD

**Issue by Kingem39p** [Pirate-Crew/IPTV#32]
Salve.

eseguendo " git clone git@github.com:Pinperepette/IPTV.git ", mi da il seguente errore:

Cloning into 'IPTV'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

quindi devo obbligatoriamente scaricarlo e caricarlo manualmente.

**Comment by ludo237** [comment]
Usa l'indirizzo HTTPs per i clone in modalità anonimo

**Comment by Kingem39p** [comment]
usando l'https mi scarica la versione tua, dove non c'è iptv_gui.py e tutti gli altri file.

**Comment by ludo237** [comment]
Dopo fai git checkout per cambiare branch
