### ISSUE TITLE
The Code doesn't work

### ISSUE THREAD

**Issue by finnishhacker** [Pirate-Crew/IPTV#33]
I tried everything. This code doesn't give me any links when i try to search for links, it just gives me an error 503. Also, when i try the GUI, no matter what link i try it keeps giving me the same error about 8919 lines or something. So, nothing works, no bruteforce not anything at all. Please fix this code as it seems like a very good idea :)

**Comment by qwerty159** [comment]
OS Installed?

**Comment by finnishhacker** [comment]
Windows 7

**Comment by Armax** [comment]
https://github.com/Pirate-Crew/IPTV-Sharp use the windows version, you don't need python or other things for this
