### ISSUE TITLE
Problema con Windows

### ISSUE THREAD

**Issue by faber93** [Pirate-Crew/IPTV#34]
Salve, inanzitutto complimenti al team per il lavoro svolto.
Ho un problema con Windows, appena cerco i server me li trova tuttavia quando prova l'attacco quest'ultimo fallisce sempre. a volte come errore mi da "ops! something went wrong"  altre volte invece "cannot open the current language file.Try another one"
Con la dev,invece, inserendo manualmente qualche server mi ha trovato degli account, ma dopo ché li trova si ferma e non prova le altre combinazioni. Nella cartella output non si crea niente e nel cmd mi compare questo errore 
![immagine](https://cloud.githubusercontent.com/assets/16991802/12724289/89cda7e8-c90d-11e5-8c7b-de15268d4286.png)

![immagine2](https://cloud.githubusercontent.com/assets/16991802/12724208/2d2d4854-c90d-11e5-958c-8252fa6c5aa5.png)

**Comment by Tonyrock90** [comment]
idem su windows

**Comment by qwerty159** [comment]
Prova ad avviare il prompt dei comandi con i privilegi d'amministratore e riprova.

**Comment by ludo237** [comment]
@Pinperepette @Armax voi avete lavorato su Windows?

**Comment by faber93** [comment]
> Prova ad avviare il prompt dei comandi con i privilegi d'amministratore e riprova.

Fatto,non funge!

 con Ubuntu ci sono riuscito anche se dopo un certo numero di tentativi il programmino non risponde.

**Comment by Armax** [comment]
https://github.com/Pirate-Crew/IPTV-Sharp windows version
