### ISSUE TITLE
ascoltate è urgente

### ISSUE THREAD

**Issue by guglyy** [Pirate-Crew/IPTV#35]
Ho scaricato sia python e sia pyqt per windows ma poi non riesco a fare il procedimento di clonare mi potete aiutare grazie

**Comment by Armax** [comment]
https://github.com/Pirate-Crew/IPTV-Sharp usa questa è apposta per windows e non richiede python

**Comment by guglyy** [comment]
Quando vado per attaccare mi dice ad alcuni il programma ha smesso di funzionare mentre ad altri aspetto 5 10 minuti e mi dice eccezione non gestita nell'applicazione fare click su continuare per ignorare l'errore e tentare di proseguire ma io premo Continua ma non succede niente quindi che fare??
