### ISSUE TITLE
Problem with google module

### ISSUE THREAD

**Issue by SlaSerX** [Pirate-Crew/IPTV#52]
Hello i install google-cloud couse dont have a google and now take this err

etching URLs plase wait...
Traceback (most recent call last):
  File "iptv.py", line 39, in <module>
    cr.search_links()
  File "/root/l33t/IPTV/iptv/Crawler.py", line 62, in search_links
    for url in google.search(self.searchString, num=30, stop=1):
AttributeError: 'module' object has no attribute 'search'

**Comment by jeafke** [comment]
edit 
`        #for url in google.search(self.searchString, num=30, stop=1):
        for url in googlesearch.search(self.searchString, num=30, stop=1):`

**Comment by SlaSerX** [comment]
Thx i will try now

**Comment by SlaSerX** [comment]
Done i fix it just need to add import googlesearch

Thx for supp

**Comment by erotavlas85** [comment]
Hi,
I have the same problem as you. Your solution does not work for me. I'm using python 3.5.2.
Thank you

**Comment by SlaSerX** [comment]
cant be work what err give u ? paste error

2018-02-05 10:58 GMT+02:00 erotavlas85 <notifications@github.com>:

**Comment by erotavlas85** [comment]
``Please select an option: 1
Fetching URLs plase wait...
Traceback (most recent call last):
  File "iptv.py", line 39, in <module>
    cr.search_links()
  File "/home/tore/Desktop/IPTV-master/iptv/Crawler.py", line 63, in search_links
    for url in googlesearch.search(self.searchString, num=30, stop=1):
AttributeError: module 'googlesearch' has no attribute 'search'

**Comment by SlaSerX** [comment]
Sure u load new module ?

**Comment by erotavlas85** [comment]
Yes, these are the first rows of Crawler.py
import urllib
import google
import googlesearch
import time
import pyprind
import os
import random
from urllib.parse import urlparse

**Comment by SlaSerX** [comment]
try run script with python2 not with python3
