### ISSUE TITLE
problem import google kali linux FIXED

### ISSUE THREAD

**Issue by hacktoolspack** [Pirate-Crew/IPTV#57]
I have a problem in kali linux for module google 2.0.1 in crawler.py

Traceback (most recent call last):
  File "iptv.py", line 2, in <module>
    import Crawler
  File "/root/Bureau/IPTV/iptv/Crawler.py", line 2, in <module>
    import google
ImportError: No module named google

**Comment by hacktoolspack** [comment]
I have found the problem

**Comment by hacktoolspack** [comment]
just install : search-google

**Comment by italiaforza3** [comment]
http://tvservice.pro/get.php?username=911283583508&password=dz9TQYkcE12yDoE&type=m3u_plus&output=mpegts

**Comment by hacktoolspack** [comment]
thanks

Le dim. 16 juin 2019 à 01:45, italiaforza3 <notifications@github.com> a
écrit :

**Comment by bushyiv** [comment]
How to install 'search-google' ?  Web search only comes back with googler.

**Comment by Delfioh** [comment]
what about [DEPRECATED] you all don't get
